apiVersion: apps/v1
kind: Deployment
metadata:
  name: emptydir-deploy
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
      - name: cache-volume
        emptyDir: {}
      containers:
      - image: nginx
        name: nginx-container
        volumeMounts:
        - name: cache-volume
          mountPath: /cache
