apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs-pv1
spec:
  storageClassName: manual     #It must match the storage class of the PV
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
