apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-affinity
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-affinity
  template:
    metadata:
      labels:
        app: node-affinity
    spec:
      containers:
      - name: k8s-demo
        image: nginx
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: tier
                operator: In           #In, NotIn, Exists, DoesNotExist. Gt, and Lt.
                values:
                - frontend
          - weight: 2
            preference:
              matchExpressions:
              - key: disktype
                operator: In
                values:
                - ssd
