apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server1
spec:
  selector:
    matchLabels:
      app: web-store
  replicas: 4
  template:
    metadata:
      labels:
        app: web-store
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - web-store
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: web-app
        image: nginx
