apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: nginx-config
      mountPath: /master-config
  volumes:
  - name: nginx-config
    configMap:
      name: game-config
      items:
      - key: game.properties	#Its a Filename
        path: game.conf
      - key: ui.properties	#Its a Filename
        path: ui.conf
