apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
  - name: test-container
    image: nginx
    env:
    - name: SPECIAL_LEVEL_KEY2
      valueFrom:
        configMapKeyRef:
          name: my-configa
          key: key2
    - name: SPECIAL_LEVEL_KEY3
      valueFrom:
        configMapKeyRef:
          name: my-configa
          key: key3
  restartPolicy: Never
