apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  namespace: default
  labels:
    app: nginx-rs
    tier1: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-rs
#      tier1: frontend
    matchExpressions:
      - {key: tier1, operator: In, values: [frontend]}
#      - {key: app, operator: In, values: [nginx]}
  template:
    metadata:
      name: poddemo
      deletionGracePeriodSeconds: 60
      labels:
        app: nginx-rs
        tier1: frontend
    spec:
      containers:
      - name: nginx-container
        image: nginx
        ports:
        - containerPort: 80
        args:
        - /bin/bash
        - -c
        - touch hello.txt; sleep 20; rm -f hello.txt; sleep 200;
        livenessProbe:
          exec:
            command:
            - cat
            - hello.txt
          initialDelaySeconds: 5
          periodSeconds: 3

