apiVersion: v1
kind: Pod
metadata:
  name: dynamic-new-pod
spec:
  volumes:
  - name: host-volume
    persistentVolumeClaim:
      claimName: pvc1
  containers:
  - image: nginx
    name: nginx-con
    volumeMounts:
    - name: host-volume
      mountPath: /mydata
