apiVersion: v1
kind: Service
metadata:
  name: headless-svc
  labels:
    app: nginx-deploy
spec:
  clusterIP: None # <= Don't forget!!
  selector:
    app: nginx-deploy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
