apiVersion: v1
kind: Service
metadata:
  name: regular-svc
  labels:
    app: livenessprobe
spec:
  selector:
    app: livenessprobe
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

