apiVersion: v1
kind: Pod
metadata:
  deletionGracePeriodSeconds: 10
  namespace: default
  name: first-pod
  labels:
    app: web
    tier: frontend    
spec:
  containers:
  - image: nginx
    name: first-con
    env:
    - name: USER
      value: ram
    - name: PASSWORD
      value: p@ssw0rd
    ports:
    - containerPort: 80
  terminationGracePeriodSeconds: 10
